---
version: '3.1'

services:
  zookeeper:
    image: arm64v8/zookeeper:3.8-temurin
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CREATE_TOPICS: Order:1:1,MigratedOrders:1:1

  mysql:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: order-legacy
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: order-legacy-username
      MYSQL_PASSWORD: order-legacy-password
      MYSQL_ROOT_PASSWORD: order-legacy-root-password

  elasticsearch:
    image: elasticsearch:8.8.1
    depends_on:
      - kafka
      - mysql
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  debezium-connect:
    image: debezium/connect:2.4
    depends_on:
      - elasticsearch
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
  logstash:
    image: logstash:8.8.1
    depends_on:
      - elasticsearch
      - debezium-connect
    ports:
      - "5001:5000"
    volumes:
      - ./infra/logstash/config:/usr/share/logstash/config
      - ./infra/logstash/pipeline:/usr/share/logstash/pipeline
  debezium-ui:
    image: debezium/debezium-ui
    container_name: debezium-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CONNECT_URIS: http://debezium-connect:8083
    depends_on:
      - debezium-connect
  kibana:
    image: kibana:8.8.1
    depends_on:
      - elasticsearch
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - "5601:5601"

volumes:
  es_data:
    driver: local
  kibana-data:
    driver: local